image_width: 640
image_height: 480
camera_name: hik
camera_matrix:
  rows: 3
  cols: 3
  data: [507.7336523134547, 0.0, 318.9566637248697, 0.0, 514.8480312954117, 250.0402768087606, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 8
  data: [0.1696047227888695, -0.04498856233139812, -0.0002916828774435363, 0.0004252043803182309, -0.3437555673313782, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [507.7336523134547, 0.0, 318.9566637248697, 0.0, 0.0, 514.8480312954117, 250.0402768087606, 0.0, 0.0, 0.0, 1.0, 0.0]
