image_width: 640
image_height: 480
camera_name: hik
camera_matrix:
  rows: 3
  cols: 3
  data: [485.7565256827494, 0.0, 314.0081964588899, 0.0, 492.2478037855774, 234.8706239915959, 0.0, 0.0, 1.0]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 8
  data: [0.1215498839685498, -0.05710544028580029, -0.001281692827042968, -0.006945578888444643, -0.1639429337684638, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [0.999978, 0.002789, -0.006046, -0.002816, 0.999986, -0.004401, 0.006034, 0.004417, 0.999972]
projection_matrix:
  rows: 3
  cols: 4
  data: [485.7565256827494, 0.0, 314.0081964588899, 0.0, 0.0, 492.2478037855774, 234.8706239915959, 0.0, 0.0, 0.0, 1.0, 0.0]
